<!-- Formulaire de modification d'un artist -->
<?php if ($picture['error'] == true) : ?>
    <div class="alert alert-danger w-25 text-center container" role="alert">
        <?= $picture['msgError'] ?>
    </div>
<?php endif; ?>
<form action=<?= ART_EDIT ?> method="POST" enctype="multipart/form-data" class='container'>
    <input type="hidden" name="id" value="<?= $_SESSION['data']['id'] ?>">
    <div class="form-group">
        <label for="lastName">Nom</label>
        <input type="text" class="form-control" id="lastName" name="lastName" value="<?= $_SESSION['data']['lastname'] ?>">
    </div>
    <div class="form-group">
        <label for="firstName">Prénom</label>
        <input type="text" class="form-control" id="firstName" name="firstName" value="<?= $_SESSION['data']['firstname'] ?>">
    </div>
    <div class="form-group">
        <label for="pseudo">Nom d'artiste</label>
        <input type="text" class="form-control" id="pseudo" name="pseudo" value="<?= $_SESSION['data']['nickname'] ?>">
    </div>
    <div class="form-group">
        <!-- Donnée sur l'ancienne image -->
        <input type="hidden" name="lastpicture" value="<?= $_SESSION['data']['picture'] ?>">
        <small class="form-text text-muted">Image actuelle</small>
        <img src=<?= FILE . '/' . PIC_ART . '/' . $_SESSION['data']['picture'] ?> alt="" style="width:15rem; height: 15rem;"><br>
        <label for="picture">Modifier l'image</label>
        <input type="hidden" name="MAX_FILE_SIZE" value="1000000" />
        <input type="file" class="form-control-file" id="picture" name="picture">

    </div>
    <button type="submit" class="btn btn-primary">Envoyer</button>
</form>