<table class="table container mt-5">
    <thead>
        <tr>
            <th scope="col" class="auto">Image</th>
            <th scope="col">Titre de l'évènement</th>
            <th scope="col">Description</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($events as $event) : ?>
            <tr>
                <td><img src=<?= FILE_PIC . '/' . PIC_EVENT . '/' . $event['eve_picture'] ?> alt="" class="card-img" style="width:15rem; height: 15rem;"></td>
                <td><?= substr_replace($event['eve_title'], '...', 20) ?></td>
                <td><?= substr_replace($event['eve_description'], '...', 50) ?></td>
                <td>
                    <a href=<?= EVE_DELETE ?> data-toggle="modal" data-target="#delete" data-id="<?= $event['eve_id'] ?>" class="btn btn-primary mr-3">Supprimer</a>
                    <a href=<?= EVE_EDIT_ID . $event['eve_id'] ?> class="btn btn-primary">Editer</a>
                </td>
            </tr>
        <?php endforeach ?>
    </tbody>
</table>